osso-abook-contact-field: if no telepathy account is availbe to handel tel and sms, try hildon-mime.
maemo-leste/osso-abook pull request #2
Opened 2023-09-27 21:37 UTC by IMbackK

This allows abook to be more useful with non-telepathy dialers such as sphone-ofono or phosh calls

2023-09-27 21:39 UTC, IMbackK commented
this requires https://github.com/maemo-leste/libhildonmime/pull/5

2023-10-03 14:12 UTC, freemangordon requested changes

2023-10-03 14:12 UTC, freemangordon commented on lib/osso-abook-contact-field.c
> +        rv = request_channel(account, OSSO_ABOOK_CONTACT_ACTION_TEL,
rv = request_channel(account, OSSO_ABOOK_CONTACT_ACTION_SMS, values->data, &error);

2023-10-03 14:12 UTC, freemangordon commented on lib/osso-abook-contact-field.c
> +      if (TP_IS_ACCOUNT(account))
I think a better code would be:

if (TP_IS_ACCOUNT(account))
         rv = request_channel(account, OSSO_ABOOK_CONTACT_ACTION_TEL, values->data, &error);

if (!rv)
        rv = contact_action_tel_as_uri(parent, values->data);

2023-10-03 14:12 UTC, freemangordon commented on lib/osso-abook-contact-field.c
> +        rv = request_channel(account, OSSO_ABOOK_CONTACT_ACTION_TEL,
same "better code" note as above

2023-10-03 14:12 UTC, freemangordon commented on lib/osso-abook-contact-field.c
> +  HildonURIAction *action = hildon_uri_get_xdg_action();
I am not sure we shall prefer xdg-open  here, lets leave libhidonmime decide for us

2024-08-26 15:34 UTC, closed without merging